### ISSUE TITLE
knife cluster launch --bootstrap seems to be missing the "bootstrap" part in v4

### ISSUE THREAD

**Issue by nickmarden** [infochimps-labs/ironfan#159]
It appears that in some part of the migration to v4 (perhaps in 8940a19d, but the git history is a bit muddled), the perform_after_launch_tasks code was completely commented out with no replacement.

For the life of me, I can't figure out how to bootstrap servers any more. Such things as `knife cluster launch --bootstrap CLUSTER-FACET-INDEX` which used to work, now result in a running server with no Chef client and no Ironfan volume configuration.

Is this an expected result of the migration? Are there other commands that I should be running?

**Comment by temujin9** [comment]
Nick:

My apologies - that part was indeed not reimplemented. We don't bootstrap much internally (we use pre-bootstrapped images instead), so I hadn't been reminded of the absence. I'll get to work on it ASAP, and it should make it into one of the next point releases.

**Comment by temujin9** [comment]
Incidentally, you may be able to bootstrap those instances separately, using `knife cluster bootstrap`.

**Comment by nickmarden** [comment]
Hi @temujin9, I tried your suggestion of `knife cluster bootstrap` and I got this:

```
[nick@nick-mba ironfan-homebase] (nick/devops/ironfan_v4_migration)$ knife cluster bootstrap nsom -VV
DEBUG: Using configuration from /Users/nick/.chef/knife.rb
Inventorying servers in nsom cluster, all facets, all servers
INFO: Loading cluster /Users/nick/workspace/ironfan-homebase/satisfaction/clusters/nsom.rb
DEBUG: Signing the request as nick_marden
DEBUG: Sending HTTP Request via GET to api.opscode.com:443/organizations/satisfaction/search/client
DEBUG: decompressing gzip response
DEBUG: Signing the request as nick_marden
DEBUG: Sending HTTP Request via GET to api.opscode.com:443/organizations/satisfaction/search/node
DEBUG: decompressing gzip response
DEBUG: Signing the request as nick_marden
DEBUG: Sending HTTP Request via GET to api.opscode.com:443/organizations/satisfaction/search/role
DEBUG: decompressing gzip response
DEBUG: Nothing to do for #<Ironfan::Provider::ChefServer::Client:0x007fa9abd6e528>.on_correlate(#<Ironfan::Broker::Computer:0x007fa9abd3f160>), skipping
DEBUG: Nothing to do for #<Ironfan::Provider::ChefServer::Role:0x007fa9abd99fc0>.on_correlate(#<Ironfan::Broker::Computer:0x007fa9abd3f160>), skipping
DEBUG: Nothing to do for #<Ironfan::Provider::ChefServer::Role:0x007fa9abd99570>.on_correlate(#<Ironfan::Broker::Computer:0x007fa9abd3f160>), skipping
DEBUG: Nothing to do for #<Ironfan::Provider::Ec2::Machine:0x007fa9b085fdc0>.on_correlate(#<Ironfan::Broker::Computer:0x007fa9abd3f160>), skipping
DEBUG: Nothing to do for #<Ironfan::Provider::Ec2::KeyPair:0x007fa9af2ea490>.on_correlate(#<Ironfan::Broker::Computer:0x007fa9abd3f160>), skipping
DEBUG: Nothing to do for #<Ironfan::Provider::Ec2::SecurityGroup:0x007fa9b080dd90>.on_correlate(#<Ironfan::Broker::Computer:0x007fa9abd3f160>), skipping
DEBUG: Nothing to do for #<Ironfan::Provider::Ec2::SecurityGroup:0x007fa9b08138f8>.on_correlate(#<Ironfan::Broker::Computer:0x007fa9abd3f160>), skipping
DEBUG: Nothing to do for Ironfan::Provider::ChefServer::Client.validate_computer!(#<Ironfan::Broker::Computer:0x007fa9abd3f160>), skipping
DEBUG: Nothing to do for Ironfan::Provider::ChefServer::Role.validate_computer!(#<Ironfan::Broker::Computer:0x007fa9abd3f160>), skipping
DEBUG: Nothing to do for Ironfan::Provider::Ec2::Machine.validate_computer!(#<Ironfan::Broker::Computer:0x007fa9abd3f160>), skipping
DEBUG: Nothing to do for Ironfan::Provider::Ec2::KeyPair.validate_computer!(#<Ironfan::Broker::Computer:0x007fa9abd3f160>), skipping
DEBUG: Nothing to do for Ironfan::Provider::Ec2::SecurityGroup.validate_computer!(#<Ironfan::Broker::Computer:0x007fa9abd3f160>), skipping
DEBUG: Nothing to do for Ironfan::Provider::ChefServer::Client.validate_resources!([#<Ironfan::Broker::Computer(resources=c{ client, node, role__nsom_cluster, role__nsom_s, machine, key_pair, security_group__systemwide, security_group__ssh }, drives=c{ root, ephemeral0 }, providers=c{ chef, iaas }, server=#<Ironfan::Dsl::Server>)>]), skipping
DEBUG: Nothing to do for Ironfan::Provider::ChefServer::Node.validate_resources!([#<Ironfan::Broker::Computer(resources=c{ client, node, role__nsom_cluster, role__nsom_s, machine, key_pair, security_group__systemwide, security_group__ssh }, drives=c{ root, ephemeral0 }, providers=c{ chef, iaas }, server=#<Ironfan::Dsl::Server>)>]), skipping
DEBUG: Nothing to do for Ironfan::Provider::ChefServer::Role.validate_resources!([#<Ironfan::Broker::Computer(resources=c{ client, node, role__nsom_cluster, role__nsom_s, machine, key_pair, security_group__systemwide, security_group__ssh }, drives=c{ root, ephemeral0 }, providers=c{ chef, iaas }, server=#<Ironfan::Dsl::Server>)>]), skipping
DEBUG: Nothing to do for Ironfan::Provider::Ec2::EbsVolume.validate_resources!([#<Ironfan::Broker::Computer(resources=c{ client, node, role__nsom_cluster, role__nsom_s, machine, key_pair, security_group__systemwide, security_group__ssh }, drives=c{ root, ephemeral0 }, providers=c{ chef, iaas }, server=#<Ironfan::Dsl::Server>)>]), skipping
DEBUG: Nothing to do for Ironfan::Provider::Ec2::KeyPair.validate_resources!([#<Ironfan::Broker::Computer(resources=c{ client, node, role__nsom_cluster, role__nsom_s, machine, key_pair, security_group__systemwide, security_group__ssh }, drives=c{ root, ephemeral0 }, providers=c{ chef, iaas }, server=#<Ironfan::Dsl::Server>)>]), skipping
DEBUG: Nothing to do for Ironfan::Provider::Ec2::SecurityGroup.validate_resources!([#<Ironfan::Broker::Computer(resources=c{ client, node, role__nsom_cluster, role__nsom_s, machine, key_pair, security_group__systemwide, security_group__ssh }, drives=c{ root, ephemeral0 }, providers=c{ chef, iaas }, server=#<Ironfan::Dsl::Server>)>]), skipping
  +----------+-------+---------+----------+------------+------+------------+---------------+---------------+------------+--------------+--------------+---------+-----------+------------+
  | Name     | Chef? | State   | Flavor   | AZ         | Env  | MachineID  | Public IP     | Private IP    | Created On | Image        | Volumes      | SSH Key | Startable | Launchable |
  +----------+-------+---------+----------+------------+------+------------+---------------+---------------+------------+--------------+--------------+---------+-----------+------------+
  | nsom-s-0 | yes   | running | m1.small | us-west-2a | nsom | i-e13e41d2 | 54.245.31.113 | 10.252.165.92 | 2012-09-18 | ami-ca038cfa | vol-3095e816 | nsom    | no        | no         |
  +----------+-------+---------+----------+------------+------+------------+---------------+---------------+------------+--------------+--------------+---------+-----------+------------+
/Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/gems/ironfan-4.0.5/lib/chef/knife/ironfan_knife_common.rb:55:in `relevant?': undefined method `exists?' for #<Ironfan::Broker::Computer:0x007fa9abd3f160> (NoMethodError)
    from /Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/gems/ironfan-4.0.5/lib/chef/knife/ironfan_knife_common.rb:75:in `block in get_relevant_slice'
    from /Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/gems/ironfan-4.0.5/lib/ironfan/broker/computer.rb:275:in `select'
    from /Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/gems/ironfan-4.0.5/lib/ironfan/broker/computer.rb:275:in `select'
    from /Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/gems/ironfan-4.0.5/lib/chef/knife/ironfan_knife_common.rb:75:in `get_relevant_slice'
    from /Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/gems/ironfan-4.0.5/lib/chef/knife/ironfan_script.rb:45:in `run'
    from /Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/gems/chef-0.10.10/lib/chef/knife.rb:402:in `run_with_pretty_exceptions'
    from /Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/gems/chef-0.10.10/lib/chef/knife.rb:168:in `run'
    from /Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/gems/chef-0.10.10/lib/chef/application/knife.rb:123:in `run'
    from /Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/gems/chef-0.10.10/bin/knife:25:in `<top (required)>'
    from /Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/bin/knife:23:in `load'
    from /Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/bin/knife:23:in `<main>'
```

**Comment by temujin9** [comment]
Sorry about that; let me know if this one doesn't work well for you.

**Comment by nickmarden** [comment]
Hi @temujin9, that's much better although I was forced to say

`knife cluster launch --bootstrap --template-file ...`

because the code was not autodetecting the :bootstrap_distro information in my knife-org.rb file.

I'm still tracking down an issue that occurred during the bootstrapping process itself, but I think it's my problem and not yours.

**Comment by temujin9** [comment]
I usually see bootstrap_distro in the cluster's cloud statement, not the knife-org. Am I missing something that promises it can provide a default?

**Comment by nickmarden** [comment]
We had followed the example of this file:

https://github.com/satisfaction/ironfan-homebase/blob/master/knife/example-credentials/knife-org.rb

lines 91-95. They were working before; now the :bootstrap_distro field is no longer passed into the Chef gem during the bootstrapping process.

**Comment by nickmarden** [comment]
Oh, worth noting: I'm using chef-10.14.2 and the place where surprising behavior is happening is

https://github.com/opscode/chef/blob/master/chef/lib/chef/knife/bootstrap.rb

line 170 - config[:bootstrap_template] is empty, and the whole thing bombs out thusly:

```
Can not find bootstrap definition for 
WARNING: No such file or directory
WARNING: ["/Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/gems/chef-10.14.2/lib/chef/knife/bootstrap.rb:151:in `find_template'", "/Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/gems/chef-10.14.2/lib/chef/knife/bootstrap.rb:170:in `run'", "/Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/gems/ironfan-4.0.9/lib/chef/knife/ironfan_knife_common.rb:147:in `run_bootstrap'", "/Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/gems/ironfan-4.0.9/lib/chef/knife/cluster_launch.rb:114:in `perform_after_launch_tasks'", "/Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/gems/ironfan-4.0.9/lib/chef/knife/cluster_launch.rb:86:in `block in run'", "/Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/gems/ironfan-4.0.9/lib/ironfan.rb:32:in `block (2 levels) in parallel'"]
```

**Comment by temujin9** [comment]
Would you mind opening separate tickets for those two? They look like disparate issues, and I've got some coders looking to help with bug-fixes on this end.

**Comment by nickmarden** [comment]
Sure, will do.
