### ISSUE TITLE
knife cluster proxy does not function

### ISSUE THREAD

**Issue by fractaloop** [infochimps-labs/ironfan#162]
When attempting to generate a proxy config for a node, there is an exception:

```
Exception: NoMethodError: undefined method `sshable?' for #<Ironfan::Broker::Computer:0x007fd61b120860>
```

This ends up being caused by https://github.com/infochimps-labs/ironfan/blob/master/lib/chef/knife/cluster_proxy.rb#L51

By changing the Chef::Knife::ClusterProxy#relevant? to `server.machine.sshable?` it will always return false even if the machine is sshable.

I don't have a good fix for this. I leave this to your discretion.

**Comment by mrflip** [comment]
working on this.

**Comment by fractaloop** [comment]
Any progress on this Flip?

**Comment by temujin9** [comment]
@mrflip - unassigning this from you for now; I've got another offer to fix this pending, and no word from you in a month.

**Comment by temujin9** [comment]
@fractaloop could you check whether this lets you do the proxy, or whether there are further bugs? Ask me if you need help putting a homebase into testing mode to check this.

**Comment by fractaloop** [comment]
Woot it fixed it! Thanks!

However, right before "Reconciling DSL and provider information" I get some errors about the ELBs.

```
WARNING: Error running Ironfan::Provider::Ec2::ElasticLoadBalancer[adaptee,bogus]:
WARNING: Operation timed out - SSL_connect (Errno::ETIMEDOUT)
ERROR: Operation timed out - SSL_connect (Errno::ETIMEDOUT) (Excon::Errors::SocketError)
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/excon-0.16.7/lib/excon/ssl_socket.rb:57:in `connect'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/excon-0.16.7/lib/excon/ssl_socket.rb:57:in `initialize'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/excon-0.16.7/lib/excon/connection.rb:364:in `new'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/excon-0.16.7/lib/excon/connection.rb:364:in `socket'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/excon-0.16.7/lib/excon/connection.rb:195:in `request_kernel'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/excon-0.16.7/lib/excon/connection.rb:103:in `request'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fog-1.6.0/lib/fog/core/connection.rb:20:in `request'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fog-1.6.0/lib/fog/aws/elb.rb:184:in `_request'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fog-1.6.0/lib/fog/aws/elb.rb:179:in `request'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fog-1.6.0/lib/fog/aws/requests/elb/describe_load_balancers.rb:61:in `describe_load_balancers'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fog-1.6.0/lib/fog/aws/models/elb/load_balancers.rb:18:in `all'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fog-1.6.0/lib/fog/core/collection.rb:130:in `lazy_load'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fog-1.6.0/lib/fog/core/collection.rb:18:in `each'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/bundler/gems/ironfan-349fb48dde1f/lib/ironfan/provider/ec2/elastic_load_balancer.rb:35:in `load!'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/bundler/gems/ironfan-349fb48dde1f/lib/ironfan/provider.rb:36:in `block in load'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/bundler/gems/ironfan-349fb48dde1f/lib/ironfan.rb:35:in `block (3 levels) in parallel'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/bundler/gems/ironfan-349fb48dde1f/lib/ironfan.rb:134:in `safely'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/bundler/gems/ironfan-349fb48dde1f/lib/ironfan.rb:34:in `block (2 levels) in parallel'
ERROR: /Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/excon-0.16.7/lib/excon/ssl_socket.rb:57:in `connect'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/excon-0.16.7/lib/excon/ssl_socket.rb:57:in `initialize'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/excon-0.16.7/lib/excon/connection.rb:364:in `new'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/excon-0.16.7/lib/excon/connection.rb:364:in `socket'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/excon-0.16.7/lib/excon/connection.rb:195:in `request_kernel'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/excon-0.16.7/lib/excon/connection.rb:103:in `request'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fog-1.6.0/lib/fog/core/connection.rb:20:in `request'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fog-1.6.0/lib/fog/aws/elb.rb:184:in `_request'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fog-1.6.0/lib/fog/aws/elb.rb:179:in `request'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fog-1.6.0/lib/fog/aws/requests/elb/describe_load_balancers.rb:61:in `describe_load_balancers'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fog-1.6.0/lib/fog/aws/models/elb/load_balancers.rb:18:in `all'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fog-1.6.0/lib/fog/core/collection.rb:130:in `lazy_load'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/fog-1.6.0/lib/fog/core/collection.rb:18:in `each'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/bundler/gems/ironfan-349fb48dde1f/lib/ironfan/provider/ec2/elastic_load_balancer.rb:35:in `load!'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/bundler/gems/ironfan-349fb48dde1f/lib/ironfan/provider.rb:36:in `block in load'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/bundler/gems/ironfan-349fb48dde1f/lib/ironfan.rb:35:in `block (3 levels) in parallel'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/bundler/gems/ironfan-349fb48dde1f/lib/ironfan.rb:134:in `safely'
/Users/fractaloop/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/bundler/gems/ironfan-349fb48dde1f/lib/ironfan.rb:34:in `block (2 levels) in parallel'
```

**Comment by temujin9** [comment]
I'd lay money on the ELB timeout being a transient problem reaching the API in question, not anything in our code. Closing this ticket; if the later problem recurs regularly, open a new one.
