### ISSUE TITLE
rake spec complains about missing /etc/chef/client.pem

### ISSUE THREAD

**Issue by temujin9** [infochimps-labs/ironfan#242]
```
ERROR: I cannot read /etc/chef/client.pem, which you told me to use to sign requests! (Chef::Exceptions::PrivateKeyMissing)
/usr/share/ruby-rvm/gems/ruby-1.9.2-p180/gems/chef-10.16.2/lib/chef/rest/auth_credentials.rb:64:in `rescue in load_signing_key'
/usr/share/ruby-rvm/gems/ruby-1.9.2-p180/gems/chef-10.16.2/lib/chef/rest/auth_credentials.rb:60:in `load_signing_key'
/usr/share/ruby-rvm/gems/ruby-1.9.2-p180/gems/chef-10.16.2/lib/chef/rest/auth_credentials.rb:34:in `initialize'
/usr/share/ruby-rvm/gems/ruby-1.9.2-p180/gems/chef-10.16.2/lib/chef/rest.rb:64:in `new'
/usr/share/ruby-rvm/gems/ruby-1.9.2-p180/gems/chef-10.16.2/lib/chef/rest.rb:64:in `initialize'
/usr/share/ruby-rvm/gems/ruby-1.9.2-p180/gems/chef-10.16.2/lib/chef/search/query.rb:34:in `new'
/usr/share/ruby-rvm/gems/ruby-1.9.2-p180/gems/chef-10.16.2/lib/chef/search/query.rb:34:in `initialize'
/home/temujin9/Projects/InfoChimps/code/ironfan/lib/ironfan/provider/chef.rb:24:in `new'
/home/temujin9/Projects/InfoChimps/code/ironfan/lib/ironfan/provider/chef.rb:24:in `search'
/home/temujin9/Projects/InfoChimps/code/ironfan/lib/ironfan/provider/chef/node.rb:91:in `load!'
/home/temujin9/Projects/InfoChimps/code/ironfan/lib/ironfan/provider.rb:36:in `block in load'
/home/temujin9/Projects/InfoChimps/code/ironfan/lib/ironfan.rb:35:in `block (3 levels) in parallel'
/home/temujin9/Projects/InfoChimps/code/ironfan/lib/ironfan.rb:134:in `safely'
/home/temujin9/Projects/InfoChimps/code/ironfan/lib/ironfan.rb:34:in `block (2 levels) in parallel'
ERROR: /usr/share/ruby-rvm/gems/ruby-1.9.2-p180/gems/chef-10.16.2/lib/chef/rest/auth_credentials.rb:64:in `rescue in load_signing_key'
/usr/share/ruby-rvm/gems/ruby-1.9.2-p180/gems/chef-10.16.2/lib/chef/rest/auth_credentials.rb:60:in `load_signing_key'
/usr/share/ruby-rvm/gems/ruby-1.9.2-p180/gems/chef-10.16.2/lib/chef/rest/auth_credentials.rb:34:in `initialize'
/usr/share/ruby-rvm/gems/ruby-1.9.2-p180/gems/chef-10.16.2/lib/chef/rest.rb:64:in `new'
/usr/share/ruby-rvm/gems/ruby-1.9.2-p180/gems/chef-10.16.2/lib/chef/rest.rb:64:in `initialize'
/usr/share/ruby-rvm/gems/ruby-1.9.2-p180/gems/chef-10.16.2/lib/chef/search/query.rb:34:in `new'
/usr/share/ruby-rvm/gems/ruby-1.9.2-p180/gems/chef-10.16.2/lib/chef/search/query.rb:34:in `initialize'
/home/temujin9/Projects/InfoChimps/code/ironfan/lib/ironfan/provider/chef.rb:24:in `new'
/home/temujin9/Projects/InfoChimps/code/ironfan/lib/ironfan/provider/chef.rb:24:in `search'
/home/temujin9/Projects/InfoChimps/code/ironfan/lib/ironfan/provider/chef/node.rb:91:in `load!'
/home/temujin9/Projects/InfoChimps/code/ironfan/lib/ironfan/provider.rb:36:in `block in load'
/home/temujin9/Projects/InfoChimps/code/ironfan/lib/ironfan.rb:35:in `block (3 levels) in parallel'
/home/temujin9/Projects/InfoChimps/code/ironfan/lib/ironfan.rb:134:in `safely'
/home/temujin9/Projects/InfoChimps/code/ironfan/lib/ironfan.rb:34:in `block (2 levels) in parallel'
WARN: Failed to read the private key /etc/chef/client.pem: #<Errno::ENOENT: No such file or directory - /etc/chef/client.pem>
WARNING: Error running Ironfan::Provider::ChefServer::Role[adaptee,bogus]:
WARNING: I cannot read /etc/chef/client.pem, which you told me to use to sign requests!
```

**Comment by temujin9** [comment]
Added code to spec to load a fixture knife.rb; fixed.
