### ISSUE TITLE
zookeeper error

### ISSUE THREAD

**Issue by sya** [infochimps-labs/ironfan#265]
chef runs to completion when zookeeper is initially launched but then reports error:

```
[2013-03-25T20:44:48+00:00] INFO: Processing group[zookeeper] action create (zookeeper::default line 42)
[2013-03-25T20:44:48+00:00] INFO: Processing user[zookeeper] action create (zookeeper::default line 61)

================================================================================
Error executing action `create` on resource 'user[zookeeper]'
================================================================================

Chef::Exceptions::Exec
----------------------
usermod -d '/data/ebs1/zookeeper/data' zookeeper returned 8, expected 0

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/silverware/definitions/daemon_user.rb

 61:   user user_val do
 62:     uid         uid_val
 63:     gid         group_val
 64:     password    nil
 65:     shell       params[:shell]
 66:     home        params[:home]
 67:     supports    :manage_home => params[:manage_home]
 68:     action      params[:action]
 69:   end
 70: 

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/silverware/definitions/daemon_user.rb:61:in `block in from_file'

user("zookeeper") do
  params {:action=>[:create, :manage], :component=>nil, :user=>"zookeeper", :home=>"/data/ebs1/zookeeper/data", :manage_home=>false, :shell=>"/bin/false", :group=>"zookeeper", :comment=>"zookeeper daemon", :create_group=>[:create], :name=>:zookeeper}
  action [:create, :manage]
  supports {:manage_home=>false}
  retries 0
  retry_delay 2
  username "zookeeper"
  uid 305
  gid 305
  home "/data/ebs1/zookeeper/data"
  shell "/bin/false"
  cookbook_name "zookeeper"
  recipe_name "default"
end

[2013-03-25T20:44:48+00:00] ERROR: Running exception handlers
[2013-03-25T20:44:48+00:00] FATAL: Saving node information to /var/chef/cache/failed-run-data.json
[2013-03-25T20:44:48+00:00] ERROR: Exception handlers complete
[2013-03-25T20:44:48+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2013-03-25T20:44:48+00:00] FATAL: Chef::Exceptions::Exec: user[zookeeper] (zookeeper::default line 61) had an error: Chef::Exceptions::Exec: usermod -d '/data/ebs1/zookeeper/data' zookeeper returned 8, expected 0
```

Stacktrace:

```
Chef::Exceptions::Exec: user[zookeeper] (zookeeper::default line 61) had an error: Chef::Exceptions::Exec: usermod -d '/data/ebs1/zookeeper/data' zookeeper returned 8, expected 0
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/mixin/command.rb:128:in `handle_command_failures'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/mixin/command.rb:75:in `run_command'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/provider/user/useradd.rb:40:in `manage_user'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/provider/user.rb:130:in `block in action_create'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/mixin/why_run.rb:52:in `call'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/provider.rb:152:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/provider/user.rb:129:in `action_create'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/provider.rb:115:in `run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/resource.rb:593:in `run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/resource_collection.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/resource_collection.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/client.rb:378:in `converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/client.rb:420:in `do_run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/client.rb:176:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/application.rb:140:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/application/client.rb:274:in `block in run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/application/client.rb:267:in `loop'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/application/client.rb:267:in `run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/lib/chef/application.rb:72:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-10.16.4/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:23:in `load'
/usr/bin/chef-client:23:in 
```

**Comment by brandonbell** [comment]
@sya Was this on the first run of chef ?

**Comment by joshbronson** [comment]
I think that's the second run. The workaround is to run sudo sv stop zookeeper_server, run the command it mentioned and then rerun chef-client.

**Comment by brandonbell** [comment]
Is there a reason the zookeeper home directory is set?  If not, removing that portion of the cookbook would be an easy fix.

**Comment by sya** [comment]
I believe that workaround did it.
thx jbro.

**Comment by joshbronson** [comment]
It should be fixed, though :) Thanks for opening, Selene.

**Comment by brandonbell** [comment]
The problem here is that the Zookeeper default.rb recipe is setting home to node[:zookeeper][:data_dir] which is not defined when it creates the user.  Silverware falls back on the pid directory by default (node[:zookeeper][:pid_dir]).  

Volumes then sets the data_dir which causes subsequent chef runs to try to fix Zookeeper's home directory and fail because 'zookeeper' is logged in. 

The proper fix as I see it is to set the home directory to node[:zookeeper][:home_dir] in the default.rb recipe... however this will break chef runs for machines that have Zookeeper already running unless you stop Zookeeper before running chef

**Comment by brandonbell** [comment]
This is fixed.  Chef runs with Zookeeper currently installed will fail with the error above, but it will be a one time thing.  New instances and going forward this will not happen.
