### ISSUE TITLE
Server "went away", but still running

### ISSUE THREAD

**Issue by temujin9** [infochimps-labs/ironfan#271]
This is a hard-to-trigger heisenbug that results in a rogue server sitting idle in AWS:

```
WARNING: Error running :
WARNING: Reload failed, Fog::Compute::AWS::Server i-93c821f1 went away.
ERROR: Reload failed, Fog::Compute::AWS::Server i-93c821f1 went away. (Fog::Errors::Error)
/var/lib/jenkins/shared/ruby/1.9.1/gems/fog-1.10.1/lib/fog/core/model.rb:72:in `block in wait_for'
/var/lib/jenkins/shared/ruby/1.9.1/gems/fog-1.10.1/lib/fog/core/wait_for.rb:5:in `wait_for'
/var/lib/jenkins/shared/ruby/1.9.1/gems/fog-1.10.1/lib/fog/core/model.rb:65:in `wait_for'
/var/lib/jenkins/shared/ruby/1.9.1/gems/ironfan-4.9.1/lib/ironfan/provider/ec2/machine.rb:179:in `block in create!'
/var/lib/jenkins/shared/ruby/1.9.1/gems/ironfan-4.9.1/lib/ironfan.rb:134:in `safely'
/var/lib/jenkins/shared/ruby/1.9.1/gems/ironfan-4.9.1/lib/ironfan/provider/ec2/machine.rb:167:in `create!'
/var/lib/jenkins/shared/ruby/1.9.1/gems/ironfan-4.9.1/lib/ironfan/broker/computer.rb:77:in `launch'
/var/lib/jenkins/shared/ruby/1.9.1/gems/ironfan-4.9.1/lib/ironfan/broker/computer.rb:316:in `block in launch'
/var/lib/jenkins/shared/ruby/1.9.1/gems/ironfan-4.9.1/lib/ironfan.rb:35:in `block (3 levels) in parallel'
/var/lib/jenkins/shared/ruby/1.9.1/gems/ironfan-4.9.1/lib/ironfan.rb:134:in `safely'
/var/lib/jenkins/shared/ruby/1.9.1/gems/ironfan-4.9.1/lib/ironfan.rb:34:in `block (2 levels) in parallel'
```

**Comment by temujin9** [comment]
https://github.com/infochimps-labs/ironfan/commit/abdee62289865d57fcd4fc14ba6c1a4918768a56 may address this. Testing has proven difficult, as it's not obvious what combination of factors triggers the underlying bug. Leaving this open for now, until I see field reports of the patch solving the problem.

**Comment by temujin9** [comment]
http://ambam-jenkins-0.infochimps.chimpy.us:8080/job/Ironfan_Cookbooks_-_2_-_Test_and_stage/176/consoleFull shows the bug getting stomped (search for `rescue`).
