### ISSUE TITLE
Allow DOT and SLASH in ironfan

### ISSUE THREAD

**Issue by lyrixx** [infochimps-labs/ironfan#285]
I have put that the following content in my `knife.rby`

``` ruby
cloud(:ec2).security_group('insight.sensiolabs.com/admin').authorize_port_range 22..22, cidr="178.21.181.96/27"
```

And I got this when I tried to bootstrap my machine:

```
  insight.sensiolabs.com:       ensuring security group permissions
  insight.sensiolabs.com:         ensuring access from insight.sensiolabs.com to insight.sensiolabs.com
  insight.sensiolabs.com/admin:   ensuring tcp access from 88.164.118.40/32 to 80..80
/var/lib/gems/1.9.1/gems/ironfan-4.8.7/lib/ironfan/provider/ec2/security_group.rb:210:in `safely_authorize': undefined method `name' for nil:NilClass (NoMethodError)
        from /var/lib/gems/1.9.1/gems/ironfan-4.8.7/lib/ironfan/provider/ec2/security_group.rb:169:in `block in prepare!'
        from /var/lib/gems/1.9.1/gems/ironfan-4.8.7/lib/ironfan/provider/ec2/security_group.rb:153:in `each'
        from /var/lib/gems/1.9.1/gems/ironfan-4.8.7/lib/ironfan/provider/ec2/security_group.rb:153:in `prepare!'
        from /var/lib/gems/1.9.1/gems/ironfan-4.8.7/lib/ironfan/provider.rb:47:in `block in prepare!'
        from /var/lib/gems/1.9.1/gems/ironfan-4.8.7/lib/ironfan/provider.rb:46:in `each'
        from /var/lib/gems/1.9.1/gems/ironfan-4.8.7/lib/ironfan/provider.rb:46:in `prepare!'
        from /var/lib/gems/1.9.1/gems/ironfan-4.8.7/lib/ironfan/broker/computer.rb:298:in `block in group_action'
        from /var/lib/gems/1.9.1/gems/ironfan-4.8.7/lib/ironfan/broker/computer.rb:298:in `each'
        from /var/lib/gems/1.9.1/gems/ironfan-4.8.7/lib/ironfan/broker/computer.rb:298:in `group_action'
        from /var/lib/gems/1.9.1/gems/ironfan-4.8.7/lib/ironfan/broker/computer.rb:302:in `prepare'
        from /var/lib/gems/1.9.1/gems/ironfan-4.8.7/lib/chef/knife/cluster_launch.rb:87:in `run'
        from /var/lib/gems/1.9.1/gems/chef-10.24.0/lib/chef/knife.rb:408:in `run_with_pretty_exceptions'
        from /var/lib/gems/1.9.1/gems/chef-10.24.0/lib/chef/knife.rb:168:in `run'
        from /var/lib/gems/1.9.1/gems/chef-10.24.0/lib/chef/application/knife.rb:123:in `run'
        from /var/lib/gems/1.9.1/gems/chef-10.24.0/bin/knife:25:in `<top (required)>'
        from /usr/local/bin/knife:23:in `load'
        from /usr/local/bin/knife:23:in `<main>'
```

I think there is an issue with `.` or `/`. May be is miss something.

**Comment by temujin9** [comment]
Dot and slash aren't allowed in cluster names. It looks like you're trying to set DNS name; use the `route53` cookbook for that.

**Comment by temujin9** [comment]
Also: security groups are AWS Security Groups. They don't protect URLs, but machines. If you want something finer grained, you'll need to set up your own internal firewalling or password protection.

**Comment by lyrixx** [comment]
Thanks you ;)
