### ISSUE TITLE
Can not use elastic ip

### ISSUE THREAD

**Issue by lyrixx** [infochimps-labs/ironfan#298]
Hello.

I try to use an elastic ip. I went to the aws console, and I reserve an ip.
Then I put this ip in my cluster/app.rb:

``` ruby
Chef::Config[:ec2_image_info].merge!({
  # Quantal (Ubuntu 12.10)
  %w[eu-west-1 64-bit ebs raring ] => { :image_id => 'ami-63cede17', :ssh_user => 'ubuntu', :bootstrap_distro => "chef-full-ironfan"}
})

Ironfan.cluster 'git_d1' do
  cloud(:ec2) do
    permanent           false
    availability_zones  ['eu-west-1b']
    backing             'ebs'
    image_name          'raring'
    flavor              'm1.small'
    mount_ephemerals
  end

  cloud(:ec2).security_group('git_d1').authorize_port_range 22..22, cidr='0.0.0.0/0'
  cloud(:ec2).security_group('git_d1').authorize_port_range 80..80, cidr='0.0.0.0/0'
  cloud(:ec2).security_group('git_d1').authorize_port_range 443..443, cidr='0.0.0.0/0'

  # Does not work. Why ???
  # cloud(:ec2).elastic_ip '54.217.231.54'

  environment 'git_d1'

  recipe 'ubuntu'
  recipe 'apt'
  recipe 'sensiolabs_git'

  cluster_role.override_attributes({
    'ubuntu' => { 'archive_url' => 'http://eu-west-1.ec2.archive.ubuntu.com/ubuntu'},
    'build_essential' => { 'compiletime' => true }
  })
end
```

And when I launch my cluster, I got this:

```
WARNING: Error running #<Ironfan::Broker::Computer(server=#<Ironfan::Dsl::Server(name="0", run_list_items=c{ ubuntu, apt, sensiolabs_git, role[git_d1-cluster], role[git
_d1-frontend-facet] }, clouds=c{ ec2 }, volumes=c{ postgres, git }, environment="git_d1", cluster_role=#<Ironfan::Dsl::Role>, facet_role=#<Ironfan::Dsl::Role>, cluster_
name="git_d1", facet_name="frontend")>, resources=c{ elastic_ip, ebs_volume__git_d1-frontend-0-postgres, ebs_volume__git_d1-frontend-0-git, keypair, security_group__git
_admin, security_group__git_d1 }, drives=c{ postgres, git, root, ephemeral0 }, providers=c{ chef, iaas })>:
WARNING: undefined method `include?' for #<Ironfan::Dsl::Ec2:0x9466b90>
ERROR: undefined method `include?' for #<Ironfan::Dsl::Ec2:0x9466b90> (NoMethodError)
/var/lib/gems/1.9.1/gems/ironfan-4.10.4/lib/ironfan/provider/ec2/elastic_ip.rb:62:in `save!'
/var/lib/gems/1.9.1/gems/ironfan-4.10.4/lib/ironfan/broker/computer.rb:96:in `block in save'
/var/lib/gems/1.9.1/gems/ironfan-4.10.4/lib/ironfan/broker/computer.rb:96:in `each'
/var/lib/gems/1.9.1/gems/ironfan-4.10.4/lib/ironfan/broker/computer.rb:96:in `save'
/var/lib/gems/1.9.1/gems/ironfan-4.10.4/lib/ironfan/broker/computer.rb:79:in `launch'
/var/lib/gems/1.9.1/gems/ironfan-4.10.4/lib/ironfan/broker/computer.rb:316:in `block in launch'
/var/lib/gems/1.9.1/gems/ironfan-4.10.4/lib/ironfan.rb:35:in `block (3 levels) in parallel'
/var/lib/gems/1.9.1/gems/ironfan-4.10.4/lib/ironfan.rb:134:in `safely'
/var/lib/gems/1.9.1/gems/ironfan-4.10.4/lib/ironfan.rb:34:in `block (2 levels) in parallel'
ERROR: /var/lib/gems/1.9.1/gems/ironfan-4.10.4/lib/ironfan/provider/ec2/elastic_ip.rb:62:in `save!'
/var/lib/gems/1.9.1/gems/ironfan-4.10.4/lib/ironfan/broker/computer.rb:96:in `block in save'
/var/lib/gems/1.9.1/gems/ironfan-4.10.4/lib/ironfan/broker/computer.rb:96:in `each'
/var/lib/gems/1.9.1/gems/ironfan-4.10.4/lib/ironfan/broker/computer.rb:96:in `save'
/var/lib/gems/1.9.1/gems/ironfan-4.10.4/lib/ironfan/broker/computer.rb:79:in `launch'
/var/lib/gems/1.9.1/gems/ironfan-4.10.4/lib/ironfan/broker/computer.rb:316:in `block in launch'
/var/lib/gems/1.9.1/gems/ironfan-4.10.4/lib/ironfan.rb:35:in `block (3 levels) in parallel'
/var/lib/gems/1.9.1/gems/ironfan-4.10.4/lib/ironfan.rb:134:in `safely'
/var/lib/gems/1.9.1/gems/ironfan-4.10.4/lib/ironfan.rb:34:in `block (2 levels) in parallel'
WARNING: Error launching #<NoMethodError: undefined method `include?' for #<Ironfan::Dsl::Ec2:0x9466b90>>; skipping after-launch tasks
```

**Comment by andrewgoktepe** [comment]
Pull request #305 fixes this issue. 
We've been running into the same problem for months and until now we've been stuck on v4.6.1 because of it.

**Comment by temujin9** [comment]
Closing this as fixed; reopen if the issue continues with newer Ironfan versions.
