### ISSUE TITLE
knife cluster ssh does not work

### ISSUE THREAD

**Issue by mheffner** [infochimps-labs/ironfan#34]
Seems to default to the internal hostname when invoked from outside EC2? Not sure if that's why it's failing.

```
$ knife cluster ssh mycluster datanode uptime  -VV
DEBUG: Using configuration from cluster_chef/.chef/knife.rb
DEBUG: Signing the request as xxxx
DEBUG: Sending HTTP Request via GET to ..../search/node
DEBUG: Adding ip-....ec2.internal
DEBUG: Adding ip-.....ec2.internal
DEBUG: Adding ip-.....ec2.internal
DEBUG: Adding domU-.....compute-1.internal
DEBUG: establishing connection to ip-.....ec2.internal:22
/home/mheffner/.rvm/gems/ree-1.8.7-2011.03@cluster_chef/gems/chef-0.10.0/lib/chef/knife/ssh.rb:90:in `session': undefined method `each' for nil:NilClass (NoMethodError)
    from /home/mheffner/.rvm/gems/ree-1.8.7-2011.03@cluster_chef/gems/net-ssh-multi-1.0.1/lib/net/ssh/multi/session_actions.rb:37:in `join'
    from /home/mheffner/.rvm/gems/ree-1.8.7-2011.03@cluster_chef/gems/net-ssh-multi-1.0.1/lib/net/ssh/multi/session_actions.rb:37:in `sessions'
    from /home/mheffner/.rvm/gems/ree-1.8.7-2011.03@cluster_chef/gems/net-ssh-multi-1.0.1/lib/net/ssh/multi/session_actions.rb:37:in `each'
    from /home/mheffner/.rvm/gems/ree-1.8.7-2011.03@cluster_chef/gems/net-ssh-multi-1.0.1/lib/net/ssh/multi/session_actions.rb:37:in `sessions'
    from /home/mheffner/.rvm/gems/ree-1.8.7-2011.03@cluster_chef/gems/net-ssh-multi-1.0.1/lib/net/ssh/multi/session_actions.rb:81:in `open_channel'
    from /home/mheffner/.rvm/gems/ree-1.8.7-2011.03@cluster_chef/gems/chef-0.10.0/lib/chef/knife/ssh.rb:161:in `ssh_command'
    from /home/mheffner/.chef/plugins/knife/cluster_ssh.rb:151:in `run'
    from /home/mheffner/.rvm/gems/ree-1.8.7-2011.03@cluster_chef/gems/chef-0.10.0/lib/chef/knife.rb:391:in `run_with_pretty_exceptions'
    from /home/mheffner/.rvm/gems/ree-1.8.7-2011.03@cluster_chef/gems/chef-0.10.0/lib/chef/knife.rb:166:in `run'
    from /home/mheffner/.rvm/gems/ree-1.8.7-2011.03@cluster_chef/gems/chef-0.10.0/lib/chef/application/knife.rb:128:in `run'
    from /home/mheffner/.rvm/gems/ree-1.8.7-2011.03@cluster_chef/gems/chef-0.10.0/bin/knife:25
    from /home/mheffner/.rvm/gems/ree-1.8.7-2011.03@cluster_chef/bin/knife:19:in `load'
    from /home/mheffner/.rvm/gems/ree-1.8.7-2011.03@cluster_chef/bin/knife:19
```

**Comment by howech** [comment]
This is really a knife ssh issue, I think.  For the moment, the
workaround is to add the command line flag "-a ec2.public_ipv4" to get
it to use the public address instead of the fqdn.

**Comment by howech** [comment]
Ok, I just checked in some code to make this easier, mainly because my fingers have grown tired of typing "-a ec2.public_ipv4 -x howech".  You should now be able to add the following to your knife.rb file

``` ruby
knife[:ssh_address_attribute] = "ec2.public_ipv4"
knife[:ssh_user] = "howech"
```

The first line provides a default value for the "-a" attribute, instead of fqdn.  "ec2.public_ipv4" works well for ec2 instances.

The second line provides a default value for the "-x" attribute, useful when your username on the remote machine differs from the username on your local machine.
