### ISSUE TITLE
ironfan 4.12.3 || 5.0.0 = cluster_ssh = undefined method `length' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by moogoos** [infochimps-labs/ironfan#350]
4.12.2 does not exhibit this behavior but 4.12.3 and 5.0.0 does. Not sure how to get around it.

Env
centos 6.5 64bit
chef 10.32.2
ruby 1.9.3-p545
rubygems 2.2.2
ironfan 4.12.3 || 5.0.0
ohai 6.22.0

/Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/ironfan-5.0.0/lib/chef/knife/cluster_ssh.rb:75:in `print_data': undefined method`length' for nil:NilClass (NoMethodError)
    from /Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/ironfan-5.0.0/lib/chef/knife/cluster_ssh.rb:73:in `block in print_data'
    from /Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/ironfan-5.0.0/lib/chef/knife/cluster_ssh.rb:73:in`each'
    from /Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/ironfan-5.0.0/lib/chef/knife/cluster_ssh.rb:73:in `print_data'
    from /Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/ironfan-5.0.0/lib/chef/knife/cluster_ssh.rb:96:in`block (3 levels) in ssh_command'
    from /Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/net-ssh-2.8.0/lib/net/ssh/connection/channel.rb:569:in `call'
    from /Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/net-ssh-2.8.0/lib/net/ssh/connection/channel.rb:569:in`do_data'
    from /Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:566:in `channel_data'
    from /Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:465:in`dispatch_incoming_packets'
    from /Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:221:in `preprocess'
    from /Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/net-ssh-multi-1.1/lib/net/ssh/multi/server.rb:204:in`preprocess'
    from /Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/net-ssh-multi-1.1/lib/net/ssh/multi/session.rb:449:in `block in preprocess'
    from /Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/net-ssh-multi-1.1/lib/net/ssh/multi/server_list.rb:47:in`block in each'
    from /Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/net-ssh-multi-1.1/lib/net/ssh/multi/server_list.rb:45:in `each'
    from /Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/net-ssh-multi-1.1/lib/net/ssh/multi/server_list.rb:45:in`each'
    from /Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/net-ssh-multi-1.1/lib/net/ssh/multi/session.rb:449:in `preprocess'
    from /Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/net-ssh-multi-1.1/lib/net/ssh/multi/session.rb:430:in`process'
    from /Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/net-ssh-multi-1.1/lib/net/ssh/multi/session.rb:417:in `block in loop'
    from /Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/net-ssh-multi-1.1/lib/net/ssh/multi/session.rb:417:in`loop'
    from /Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/net-ssh-multi-1.1/lib/net/ssh/multi/session.rb:417:in `loop'
    from /Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/ironfan-5.0.0/lib/chef/knife/cluster_ssh.rb:110:in`ssh_command'
    from /Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/ironfan-5.0.0/lib/chef/knife/cluster_ssh.rb:132:in `_run'
    from /Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/ironfan-5.0.0/lib/chef/knife/ironfan_knife_common.rb:32:in`run'
    from /Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/ironfan-5.0.0/lib/chef/knife/cluster_kick.rb:55:in `run'
    from /Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/chef-10.32.2/lib/chef/knife.rb:408:in`run_with_pretty_exceptions'
    from /Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/chef-10.32.2/lib/chef/knife.rb:168:in `run'
    from /Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/chef-10.32.2/lib/chef/application/knife.rb:125:in`run'
    from /Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/chef-10.32.2/bin/knife:25:in `<top (required)>'
    from /Users/christian/.rbenv/versions/1.9.3-p545/bin/knife:23:in`load'
    from /Users/christian/.rbenv/versions/1.9.3-p545/bin/knife:23:in `<main>'

**Comment by nickmarden** [comment]
What command results in this error?

**Comment by moogoos** [comment]
knife cluster kick foo. Let me switch to 4.12.3 and get a little more detail.

**Comment by nickmarden** [comment]
What happens if you replace

`display_hostname = @hostname_to_ironfan_hostname[host]`

with

`display_hostname = @hostname_to_ironfan_hostname[host] || host`

?

**Comment by moogoos** [comment]
let me give er a go. queue elevator music

**Comment by nickmarden** [comment]
@meekmichael, can you think of a case where `@hostname_to_ironfan_hostname` would not include the/a host that is being `knife cluster kick`'ed?

**Comment by moogoos** [comment]
```
  #  display_hostname = @hostname_to_ironfan_hostname[host]
  display_hostname = @hostname_to_ironfan_hostname[host] || host
      if data =~ /\n/
      data.split(/\n/).each { |d| print_data(host, d, err) }
    else
      padding = @longest_ironfan_hostname - display_hostname.length
      str = ui.color(display_hostname, :cyan) + (" " * (padding + 1)) + (err ? ui.color(data, :red) : data)
      ui.msg(str)
```

/Users/christian/.rbenv/versions/1.9.3-p545/lib/ruby/gems/1.9.1/gems/ironfan-4.12.3/lib/chef/knife/cluster_ssh.rb:77:in `*': negative argument (ArgumentError)

**Comment by nickmarden** [comment]
so after this line:

`display_hostname = @hostname_to_ironfan_hostname[host] || host`

add this:

`@longest_ironfan_hostname = [ @longest_ironfan_hostname, display_hostname.length ].compact.max`

**Comment by moogoos** [comment]
Good. Too. Go. from some brief testing... Thank you again. 

I imagine this will get to HEAD at some point of which I am having issues testing in regards to realms, which are required in 6.x I believe. I will submit an issue to that as well.
