### ISSUE TITLE
knife cluster launch --bootstrap not working

### ISSUE THREAD

**Issue by mrflip** [infochimps-labs/ironfan#39]
knife cluster launch --bootstrap not working.  cluster_bootstrap.rb sets the following config variables, but cluster_launch does not. 

``` ruby
        config[:ssh_user]       = facet.cloud.ssh_user
        config[:identity_file]  = facet.cloud.ssh_identity_file
        config[:distro]         = facet.cloud.bootstrap_distro
        config[:run_list]       = facet.run_list
```

**Comment by mrflip** [comment]
When I tried specifying a template, a race condition happened (?) -- I had two nodes up, bumped `instances` to 3, and then reran as shown:

```
worblehat ~/ics/sysadmin/infochimps_chef$ knife cluster launch monkeyballs worker --bootstrap -V -V --template ~/.chef/bootstrap/ubuntu10.04-cluster_chef.erb 
DEBUG: Using configuration from /Users/flip/.chef/knife.rb
DEBUG: Signing the request as mrflip
DEBUG: Sending HTTP Request via GET to api.opscode.com:443/organizations/infochimps/search/node
  +------------+-----------+--------------+-------------------+-------------+-----------+------------+
  | Instance   | Flavor    | Image        | Availability Zone | SSH Key     | Public IP | Private IP |
  +------------+-----------+--------------+-------------------+-------------+-----------+------------+
  | i-d3a199bd | m2.xlarge | ami-cef405a7 | us-east-1d        | monkeyballs |           |            |
  +------------+-----------+--------------+-------------------+-------------+-----------+------------+

  0/1  |                                                  |  /Users/flip/.rvm/gems/ruby-1.9.2-p136/gems/excon-0.6.3/lib/excon/connection.rb:179:in `request': The instance ID 'i-d3a199bd' does not exist (Fog::Service::NotFound)                                            
    from /Users/flip/.rvm/gems/ruby-1.9.2-p136/gems/fog-0.8.2/lib/fog/core/connection.rb:20:in `request'
    from /Users/flip/.rvm/gems/ruby-1.9.2-p136/gems/fog-0.8.2/lib/fog/compute/aws.rb:272:in `request'
    from /Users/flip/.rvm/gems/ruby-1.9.2-p136/gems/fog-0.8.2/lib/fog/compute/requests/aws/create_tags.rb:35:in `create_tags'
    from /Users/flip/.rvm/gems/ruby-1.9.2-p136/gems/fog-0.8.2/lib/fog/compute/models/aws/tag.rb:27:in `save'
    from /Users/flip/.rvm/gems/ruby-1.9.2-p136/gems/fog-0.8.2/lib/fog/core/collection.rb:50:in `create'
    from /Users/flip/ics/sysadmin/cluster_chef/lib/cluster_chef/compute.rb:672:in `block in create_tags'
    from /Users/flip/ics/sysadmin/cluster_chef/lib/cluster_chef/compute.rb:671:in `each_pair'
    from /Users/flip/ics/sysadmin/cluster_chef/lib/cluster_chef/compute.rb:671:in `create_tags'
    from /Users/flip/.chef/plugins/knife/cluster_launch.rb:179:in `block (2 levels) in run'
```

**Comment by mrflip** [comment]
fixed
