### ISSUE TITLE
Limit on how much data can be sent to a newly bootstrapped node?

### ISSUE THREAD

**Issue by pcn** [infochimps-labs/ironfan#69]
/Users/pn/gems/gems/excon-0.6.6/lib/excon/connection.rb:190:in `request': RequestLimitExceeded => Request limit exceeded. (Fog::Service::Error)

I get this trying to launch a cluster of 18 nodes after adding this hack to chef, to send an encrypted data bag secret:

https://github.com/pcn/chef/commit/953170fa2cdc1df33a159745f4fb9f1de9578442

"description"=>"cluster_chef generated group PNTestCluster"}, @cloud=#<ClusterChef::Cloud::Ec2:0x1023e29e0 ...>>, "ssh"=>#<ClusterChef::Cloud::SecurityGroup:0x1023deef8 ...>}}>>}}>, @cluster=#<ClusterChef::Cluster:0x1023e3868 ...>, @fullname="PNTestCluster-knewdle-0">}>}, @fog_servers=  <Fog::AWS::Compute::Servers
    filters={}
    []

> , @aws_instance_hash={}>, @fullname="PNTestCluster-web_proxy-0">
> WARNING: 
>     18/18  |**************************************************|  1:55  
> /Users/pn/gems/gems/excon-0.6.6/lib/excon/connection.rb:190:in `request': RequestLimitExceeded => Request limit exceeded. (Fog::Service::Error)
>         from /Users/pn/gems/gems/chef-0.10.4/lib/chef/knife/core/bootstrap_context.rb:54:in`join'
>         from /Users/pn/gems/gems/chef-0.10.4/lib/chef/knife/core/bootstrap_context.rb:54:in `to_proc'
>         from /Users/pn/.chef/plugins/knife/knife_common.rb:109:in`each'
>         from /Users/pn/.chef/plugins/knife/knife_common.rb:109:in `progressbar_for_threads'
>         from /Users/pn/.chef/plugins/knife/cluster_launch.rb:99:in`run'
>         from /Users/pn/gems/gems/chef-0.10.4/lib/chef/knife.rb:391:in `run_with_pretty_exceptions'
>         from /Users/pn/gems/gems/chef-0.10.4/lib/chef/knife.rb:166:in`run'
>         from /Users/pn/gems/gems/chef-0.10.4/lib/chef/application/knife.rb:128:in `run'
>         from /Users/pn/gems/gems/chef-0.10.4/bin/knife:25
>         from /Users/pn/gems/bin/knife:19:in`load'
>         from /Users/pn/gems/bin/knife:19

How has the amount of data being sent to clients changed recently?  What is the limit I'm running into?

Thanks,

-Peter

**Comment by pcn** [comment]
I don't know if this is a printing error, or there is some circular population of data, but here's an excerpt of the tremendous volume of data I'm seeing:

926 pn@PN-mac 10:58 ~/work/cluster_chef_test $ head -1 mostofthecrap.txt 
    user_data="{\n  \"facet_index\": 0,\n  \"client_key\": \"-----BEGIN RSA PRIVATE KEY-----\nXXXXXXXXXXXXXXXXXXXXXXX[...]XXXXXXX\n-----END RSA PRIVATE KEY-----\n\",\n  \"validation_client_name\": \"chef-validator\",\n  \"chef_server\": \"http://ec2-184-72-211-88.compute-1.amazonaws.com:4000\",\n  \"run_list\": [\n    \"role[PNTestCluster_cluster]\",\n    \"role[knewton_package]\",\n    \"role[chef_client]\",\n    \"role[ssh]\",\n    \"role[PNTestCluster_kbs_Authentication]\"\n  ],\n  \"node_name\": \"PNTestCluster-kbs_Authentication-0\",\n  \"cluster_name\": \"PNTestCluster\",\n  \"facet_name\": \"kbs_Authentication\"\n}"
927 pn@PN-mac 10:58 ~/work/cluster_chef_test $ wc mostofthecrap.txt 
      56   32390 1415211 mostofthecrap.txt

That's way more than the ec2 user_data is supposed to accommodate, isn't it?  It looks like the user_data that's being shipped is all of the state in knife (multiple ClusterChef::Cluster objects, ClusterChef::Facet objects, Fog objects, I mean everything).

I'm having a real slog tracking down how this is happening, and how to minimize it.  Any pointers?

**Comment by pcn** [comment]
OK, I found the problem. There is another config option that was missing in this test.  A similar error occurred while opscode had some problems with my account yesterday, and I conflated the error messages from then with the error messages I'm getting now.  The volume of error messages and apparent user_data flood was because of the difficulty in reading and matching {}[]<>() etc.

So, not a bug!
