### ISSUE TITLE
Hadoop Demo won't launch with Version_3 branch

### ISSUE THREAD

**Issue by redbeard** [infochimps-labs/ironfan#85]
Trying to launch the cluster_chef-homebase / clusters / hadoop_demo.rb  cluster using the latest version_3 results in an exception from Fog.

```
MissingParameter => The request must contain the parameter ImageId
ERROR: MissingParameter => The request must contain the parameter ImageId (Fog::Compute::AWS::Error)
/Users/redbeard/.rvm/gems/ruby-1.9.2-p0/gems/excon-0.9.2/lib/excon/connection.rb:232:in `request_kernel'
/Users/redbeard/.rvm/gems/ruby-1.9.2-p0/gems/excon-0.9.2/lib/excon/connection.rb:89:in `request'
/Users/redbeard/.rvm/gems/ruby-1.9.2-p0/gems/fog-1.1.2/lib/fog/core/connection.rb:20:in `request'
/Users/redbeard/.rvm/gems/ruby-1.9.2-p0/gems/fog-1.1.2/lib/fog/aws/compute.rb:324:in `request'
/Users/redbeard/.rvm/gems/ruby-1.9.2-p0/gems/fog-1.1.2/lib/fog/aws/requests/compute/run_instances.rb:113:in `run_instances'
/Users/redbeard/.rvm/gems/ruby-1.9.2-p0/gems/fog-1.1.2/lib/fog/aws/models/compute/server.rb:171:in `save'
/Users/redbeard/.rvm/gems/ruby-1.9.2-p0/gems/fog-1.1.2/lib/fog/core/collection.rb:50:in `create'
/Users/redbeard/.rvm/gems/ruby-1.9.2-p0/bundler/gems/cluster_chef-ffcbc41811d8/lib/cluster_chef/fog_layer.rb:12:in `block in fog_create_server'
/Users/redbeard/.rvm/gems/ruby-1.9.2-p0/bundler/gems/cluster_chef-ffcbc41811d8/lib/cluster_chef.rb:136:in `safely'
/Users/redbeard/.rvm/gems/ruby-1.9.2-p0/bundler/gems/cluster_chef-ffcbc41811d8/lib/cluster_chef/dsl_object.rb:119:in `safely'
/Users/redbeard/.rvm/gems/ruby-1.9.2-p0/bundler/gems/cluster_chef-ffcbc41811d8/lib/cluster_chef/fog_layer.rb:11:in `fog_create_server'
/Users/redbeard/.rvm/gems/ruby-1.9.2-p0/bundler/gems/cluster_chef-ffcbc41811d8/lib/cluster_chef/server.rb:245:in `create_server'
/Users/redbeard/.rvm/gems/ruby-1.9.2-p0/bundler/gems/cluster_chef-ffcbc41811d8/lib/cluster_chef/server_slice.rb:245:in `block in delegate_to_servers'
/Users/redbeard/.rvm/gems/ruby-1.9.2-p0/bundler/gems/cluster_chef-ffcbc41811d8/lib/cluster_chef/server_slice.rb:231:in `block (2 levels) in parallelize'
```

Gemfile.lock:

```
GIT
  remote: https://github.com/infochimps/cluster_chef.git
  revision: ffcbc41811d8edbf9038c80ee0570267a0b1cce8
  branch: version_3
  specs:
    cluster_chef (3.0.9)
      chef (~> 0.10.4)
      cluster_chef-knife (= 3.0.9)
      fog (~> 1.1.1)
      formatador (~> 0.2.1)
      gorillib (~> 0.1.7)
    cluster_chef-knife (3.0.9)
      chef (~> 0.10.4)
      fog (~> 1.1.1)
      formatador (~> 0.2.1)
      gorillib (~> 0.1.7)

GEM
  remote: http://rubygems.org/
  specs:
    Platform (0.4.0)
    archive-tar-minitar (0.5.2)
    builder (3.0.0)
    bunny (0.7.8)
    chef (0.10.8)
      bunny (>= 0.6.0)
      erubis
      highline
      json (>= 1.4.4, <= 1.6.1)
      mixlib-authentication (>= 1.1.0)
      mixlib-cli (>= 1.1.0)
      mixlib-config (>= 1.1.2)
      mixlib-log (>= 1.3.0)
      moneta
      net-ssh (~> 2.1.3)
      net-ssh-multi (~> 1.1.0)
      ohai (>= 0.6.0)
      rest-client (>= 1.0.4, < 1.7.0)
      treetop (~> 1.4.9)
      uuidtools
    coderay (0.9.8)
    cucumber (1.1.4)
      builder (>= 2.1.2)
      diff-lcs (>= 1.1.2)
      gherkin (~> 2.7.1)
      json (>= 1.4.6)
      term-ansicolor (>= 1.0.6)
    diff-lcs (1.1.3)
    erubis (2.7.0)
    excon (0.9.2)
    ffi (1.0.11)
    fog (1.1.2)
      builder
      excon (~> 0.9.0)
      formatador (~> 0.2.0)
      mime-types
      multi_json (~> 1.0.3)
      net-scp (~> 1.0.4)
      net-ssh (>= 2.1.3)
      nokogiri (~> 1.5.0)
      ruby-hmac
    formatador (0.2.1)
    gherkin (2.7.1)
      json (>= 1.4.6)
    gorillib (0.1.8)
      json
    grit (2.4.1)
      diff-lcs (~> 1.1)
      mime-types (~> 1.15)
    highline (1.6.9)
    i18n (0.6.0)
    json (1.5.4)
    method_source (0.6.7)
      ruby_parser (>= 2.3.1)
    mime-types (1.17.2)
    mixlib-authentication (1.1.4)
      mixlib-log
    mixlib-cli (1.2.2)
    mixlib-config (1.1.2)
    mixlib-log (1.3.0)
    moneta (0.6.0)
    multi_json (1.0.4)
    net-scp (1.0.4)
      net-ssh (>= 1.99.1)
    net-ssh (2.1.4)
    net-ssh-gateway (1.1.0)
      net-ssh (>= 1.99.1)
    net-ssh-multi (1.1)
      net-ssh (>= 2.1.4)
      net-ssh-gateway (>= 0.99.0)
    nokogiri (1.5.0)
    ohai (0.6.10)
      mixlib-cli
      mixlib-config
      mixlib-log
      systemu (~> 2.2.0)
      yajl-ruby
    open4 (1.3.0)
    polyglot (0.3.3)
    popen4 (0.1.2)
      Platform (>= 0.4.0)
      open4 (>= 0.4.0)
    progressbar (0.9.2)
    pry (0.9.7.4)
      coderay (~> 0.9.8)
      method_source (~> 0.6.7)
      ruby_parser (>= 2.3.1)
      slop (~> 2.1.0)
    rake (0.9.2.2)
    rest-client (1.6.7)
      mime-types (>= 1.16)
    rspec (2.7.0)
      rspec-core (~> 2.7.0)
      rspec-expectations (~> 2.7.0)
      rspec-mocks (~> 2.7.0)
    rspec-core (2.7.1)
    rspec-expectations (2.7.0)
      diff-lcs (~> 1.1.2)
    rspec-mocks (2.7.0)
    ruby-hmac (0.4.0)
    ruby_parser (2.3.1)
      sexp_processor (~> 3.0)
    sexp_processor (3.0.9)
    slop (2.1.0)
    systemu (2.2.0)
    term-ansicolor (1.0.7)
    thor (0.14.6)
    treetop (1.4.10)
      polyglot
      polyglot (>= 0.3.1)
    uuidtools (2.1.2)
    vagrant (0.8.10)
      archive-tar-minitar (= 0.5.2)
      erubis (~> 2.7.0)
      i18n (~> 0.6.0)
      json (~> 1.5.1)
      net-scp (~> 1.0.4)
      net-ssh (~> 2.1.4)
      thor (~> 0.14.6)
      virtualbox (~> 0.9.1)
    veewee (0.2.2)
      cucumber (>= 1.0.0)
      highline (~> 1.6.1)
      net-ssh (~> 2.1.0)
      popen4 (~> 0.1.2)
      progressbar
      rspec (~> 2.5)
      thor (~> 0.14.6)
      vagrant (~> 0.8.2)
    virtualbox (0.9.2)
      ffi (~> 1.0.9)
    yajl-ruby (1.1.0)
    yard (0.6.8)

PLATFORMS
  ruby

DEPENDENCIES
  bundler (~> 1)
  chef (~> 0.10.4)
  cluster_chef (~> 3.0.8)!
  grit
  pry
  rake
  rspec
  vagrant (~> 0.8.8)
  veewee (~> 0.2.0)
  yard (~> 0.6.7)
```

**Comment by mrflip** [comment]
The image name left in was our internal one =sorry=

I made it a little less opinionated, but don't have a chance right now to test it out -- please reply if you hit another hitch.

**Comment by redbeard** [comment]
Thanks for fixing! 

I'm wondering if the real underlying issue is missing a clearer error message when an image name can't be resolved into an image id?

**Comment by mrflip** [comment]
Great point -- cleared up the error message. 

Will push new version of gem in a bit, going to try to run down the remaining example clusters.
